services:
  - type: web
    name: smart-content-recommender
    runtime: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt && python backend/preprocessing.py
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --app-dir backend
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
